# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeantik/programs/SecondBrainBot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeantik/programs/SecondBrainBot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeantik/programs/SecondBrainBot/CMakeFiles /home/jeantik/programs/SecondBrainBot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeantik/programs/SecondBrainBot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TelegramBot

# Build rule for target.
TelegramBot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TelegramBot
.PHONY : TelegramBot

# fast build rule for target.
TelegramBot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/build
.PHONY : TelegramBot/fast

src/ChatGPTService/src/ChatGPTService.o: src/ChatGPTService/src/ChatGPTService.cpp.o
.PHONY : src/ChatGPTService/src/ChatGPTService.o

# target to build an object file
src/ChatGPTService/src/ChatGPTService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/ChatGPTService/src/ChatGPTService.cpp.o
.PHONY : src/ChatGPTService/src/ChatGPTService.cpp.o

src/ChatGPTService/src/ChatGPTService.i: src/ChatGPTService/src/ChatGPTService.cpp.i
.PHONY : src/ChatGPTService/src/ChatGPTService.i

# target to preprocess a source file
src/ChatGPTService/src/ChatGPTService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/ChatGPTService/src/ChatGPTService.cpp.i
.PHONY : src/ChatGPTService/src/ChatGPTService.cpp.i

src/ChatGPTService/src/ChatGPTService.s: src/ChatGPTService/src/ChatGPTService.cpp.s
.PHONY : src/ChatGPTService/src/ChatGPTService.s

# target to generate assembly for a file
src/ChatGPTService/src/ChatGPTService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/ChatGPTService/src/ChatGPTService.cpp.s
.PHONY : src/ChatGPTService/src/ChatGPTService.cpp.s

src/CommunicationInterface/src/CommunicationInterface.o: src/CommunicationInterface/src/CommunicationInterface.cpp.o
.PHONY : src/CommunicationInterface/src/CommunicationInterface.o

# target to build an object file
src/CommunicationInterface/src/CommunicationInterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/CommunicationInterface/src/CommunicationInterface.cpp.o
.PHONY : src/CommunicationInterface/src/CommunicationInterface.cpp.o

src/CommunicationInterface/src/CommunicationInterface.i: src/CommunicationInterface/src/CommunicationInterface.cpp.i
.PHONY : src/CommunicationInterface/src/CommunicationInterface.i

# target to preprocess a source file
src/CommunicationInterface/src/CommunicationInterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/CommunicationInterface/src/CommunicationInterface.cpp.i
.PHONY : src/CommunicationInterface/src/CommunicationInterface.cpp.i

src/CommunicationInterface/src/CommunicationInterface.s: src/CommunicationInterface/src/CommunicationInterface.cpp.s
.PHONY : src/CommunicationInterface/src/CommunicationInterface.s

# target to generate assembly for a file
src/CommunicationInterface/src/CommunicationInterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/CommunicationInterface/src/CommunicationInterface.cpp.s
.PHONY : src/CommunicationInterface/src/CommunicationInterface.cpp.s

src/DailyService/src/DailyService.o: src/DailyService/src/DailyService.cpp.o
.PHONY : src/DailyService/src/DailyService.o

# target to build an object file
src/DailyService/src/DailyService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/DailyService/src/DailyService.cpp.o
.PHONY : src/DailyService/src/DailyService.cpp.o

src/DailyService/src/DailyService.i: src/DailyService/src/DailyService.cpp.i
.PHONY : src/DailyService/src/DailyService.i

# target to preprocess a source file
src/DailyService/src/DailyService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/DailyService/src/DailyService.cpp.i
.PHONY : src/DailyService/src/DailyService.cpp.i

src/DailyService/src/DailyService.s: src/DailyService/src/DailyService.cpp.s
.PHONY : src/DailyService/src/DailyService.s

# target to generate assembly for a file
src/DailyService/src/DailyService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/DailyService/src/DailyService.cpp.s
.PHONY : src/DailyService/src/DailyService.cpp.s

src/DatabaseService/src/DatabaseService.o: src/DatabaseService/src/DatabaseService.cpp.o
.PHONY : src/DatabaseService/src/DatabaseService.o

# target to build an object file
src/DatabaseService/src/DatabaseService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/DatabaseService/src/DatabaseService.cpp.o
.PHONY : src/DatabaseService/src/DatabaseService.cpp.o

src/DatabaseService/src/DatabaseService.i: src/DatabaseService/src/DatabaseService.cpp.i
.PHONY : src/DatabaseService/src/DatabaseService.i

# target to preprocess a source file
src/DatabaseService/src/DatabaseService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/DatabaseService/src/DatabaseService.cpp.i
.PHONY : src/DatabaseService/src/DatabaseService.cpp.i

src/DatabaseService/src/DatabaseService.s: src/DatabaseService/src/DatabaseService.cpp.s
.PHONY : src/DatabaseService/src/DatabaseService.s

# target to generate assembly for a file
src/DatabaseService/src/DatabaseService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/DatabaseService/src/DatabaseService.cpp.s
.PHONY : src/DatabaseService/src/DatabaseService.cpp.s

src/MessageProcessingService/src/MessageProcessingService.o: src/MessageProcessingService/src/MessageProcessingService.cpp.o
.PHONY : src/MessageProcessingService/src/MessageProcessingService.o

# target to build an object file
src/MessageProcessingService/src/MessageProcessingService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/MessageProcessingService/src/MessageProcessingService.cpp.o
.PHONY : src/MessageProcessingService/src/MessageProcessingService.cpp.o

src/MessageProcessingService/src/MessageProcessingService.i: src/MessageProcessingService/src/MessageProcessingService.cpp.i
.PHONY : src/MessageProcessingService/src/MessageProcessingService.i

# target to preprocess a source file
src/MessageProcessingService/src/MessageProcessingService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/MessageProcessingService/src/MessageProcessingService.cpp.i
.PHONY : src/MessageProcessingService/src/MessageProcessingService.cpp.i

src/MessageProcessingService/src/MessageProcessingService.s: src/MessageProcessingService/src/MessageProcessingService.cpp.s
.PHONY : src/MessageProcessingService/src/MessageProcessingService.s

# target to generate assembly for a file
src/MessageProcessingService/src/MessageProcessingService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/MessageProcessingService/src/MessageProcessingService.cpp.s
.PHONY : src/MessageProcessingService/src/MessageProcessingService.cpp.s

src/StorageService/src/StorageService.o: src/StorageService/src/StorageService.cpp.o
.PHONY : src/StorageService/src/StorageService.o

# target to build an object file
src/StorageService/src/StorageService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/StorageService/src/StorageService.cpp.o
.PHONY : src/StorageService/src/StorageService.cpp.o

src/StorageService/src/StorageService.i: src/StorageService/src/StorageService.cpp.i
.PHONY : src/StorageService/src/StorageService.i

# target to preprocess a source file
src/StorageService/src/StorageService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/StorageService/src/StorageService.cpp.i
.PHONY : src/StorageService/src/StorageService.cpp.i

src/StorageService/src/StorageService.s: src/StorageService/src/StorageService.cpp.s
.PHONY : src/StorageService/src/StorageService.s

# target to generate assembly for a file
src/StorageService/src/StorageService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/StorageService/src/StorageService.cpp.s
.PHONY : src/StorageService/src/StorageService.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TelegramBot.dir/build.make CMakeFiles/TelegramBot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TelegramBot"
	@echo "... src/ChatGPTService/src/ChatGPTService.o"
	@echo "... src/ChatGPTService/src/ChatGPTService.i"
	@echo "... src/ChatGPTService/src/ChatGPTService.s"
	@echo "... src/CommunicationInterface/src/CommunicationInterface.o"
	@echo "... src/CommunicationInterface/src/CommunicationInterface.i"
	@echo "... src/CommunicationInterface/src/CommunicationInterface.s"
	@echo "... src/DailyService/src/DailyService.o"
	@echo "... src/DailyService/src/DailyService.i"
	@echo "... src/DailyService/src/DailyService.s"
	@echo "... src/DatabaseService/src/DatabaseService.o"
	@echo "... src/DatabaseService/src/DatabaseService.i"
	@echo "... src/DatabaseService/src/DatabaseService.s"
	@echo "... src/MessageProcessingService/src/MessageProcessingService.o"
	@echo "... src/MessageProcessingService/src/MessageProcessingService.i"
	@echo "... src/MessageProcessingService/src/MessageProcessingService.s"
	@echo "... src/StorageService/src/StorageService.o"
	@echo "... src/StorageService/src/StorageService.i"
	@echo "... src/StorageService/src/StorageService.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

